### ISSUE TITLE
ExtractPointer空指针解析错误

### ISSUE THREAD

**Issue by aide-cloud** [duke-git/lancet#228]
```go
// You can edit this code!
// Click here and start typing.
package main

import (
	"fmt"

	"github.com/duke-git/lancet/v2/pointer"
)

func main() {
	result := pointer.ExtractPointer(nil)

	fmt.Println(result)

	// Output:
	// 1
}
```

```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x98 pc=0x4804aa]

goroutine 1 [running]:
github.com/duke-git/lancet/v2/pointer.ExtractPointer({0x0, 0x0})
	/tmp/gopath3492907256/pkg/mod/github.com/duke-git/lancet/v2@v2.3.1/pointer/pointer.go:49 +0xaa
main.main()
	/tmp/sandbox2823197783/prog.go:13 +0x17
```

**Comment by duke-git** [comment]
v2.3.2版本已修复
